/* regen-odds.js — rebuild the ODDS table from what the engine actually makes.
 *
 * The rarity table is a measurement, not a declaration. Re-run this after ANY
 * change to the engine (new composition, scene, accessory, weight tweak) and
 * paste the printed block over the existing `const ODDS = {...}` in index.html.
 *
 *   node tools/regen-odds.js ../index.html            → 40,000 random rolls
 *   node tools/regen-odds.js ../index.html 3333 1     → exactly seeds 1..3333
 *
 * The second form is the one to use once the 3,333 collection is generated:
 * it makes the placard percentages describe the real collection.
 */
const fs = require('fs');
const file = process.argv[2] || 'index.html';
const N    = +(process.argv[3] || 40000);
const FROM = +(process.argv[4] || 0);

/* pull the engine out of the page: everything from the palette table down to
   the first line of DOM wiring */
const page = fs.readFileSync(file, 'utf8');
const a = page.indexOf('const BAD=[');
const b = page.indexOf("document.getElementById('next').onclick");
if (a < 0 || b < 0) { console.error('markers not found — did index.html change shape?'); process.exit(1); }
const engine = page.slice(a, page.lastIndexOf('\n', b));

global.document = { getElementById: () => ({ setAttribute(){}, set innerHTML(v){}, get innerHTML(){return '';} }) };

const KEYS = ['subject','composition','ground','condition','surface','signature',
              'inscription','palette','figures','hands','species','accessory'];

const harness = `
  const T = {}; KEYS.forEach(k => T[k] = {});
  for (let i = 0; i < ${N}; i++) {
    SEED = ${FROM} ? (${FROM} + i) : ((i * 2654435761 + 12345) >>> 0);
    RNG = mulberry32(SEED); FORCE = null; PAL = BAD; WOB = 1; DENS = 1;
    CW = 300; CH = 300; BANNER = false; PXFORCE = null;
    generate();
    KEYS.forEach(k => { if (TR[k] === undefined) return;
      const v = String(TR[k]); T[k][v] = (T[k][v] || 0) + 1; });
  }
  module.exports = T;`;

const mod = {};
new Function('document','module','require','KEYS', engine + harness)(global.document, mod, require, KEYS);
const T = mod.exports;

const quote = v => (/^[A-Za-z_][A-Za-z0-9_]*$/.test(v) ? v : "'" + v.replace(/'/g, "\\'") + "'");

const block = KEYS.map(k => {
  let ent = T[k] || {};
  /* combinations ("brainlet + cactus") are priced by multiplying the singles
     in oddsOf, so only solo subjects are stored */
  if (k === 'subject') ent = Object.fromEntries(Object.entries(ent).filter(([v]) => !v.includes(' + ')));
  const rows = Object.entries(ent).sort((x, y) => y[1] - x[1])
    .map(([v, c]) => quote(v) + ':' + Math.max(0.0005, +(c / N).toFixed(4)));
  const lines = []; let cur = '';
  for (const r of rows) { if (cur.length + r.length + 1 > 74) { lines.push(cur.replace(/,$/, '')); cur = ''; } cur += r + ','; }
  if (cur) lines.push(cur.replace(/,$/, ''));
  return '  ' + k + ':{' + lines.join(',\n' + ' '.repeat(k.length + 5)) + '}';
}).join(',\n');

console.log('/* Measured, not declared. Regenerated by tools/regen-odds.js from');
console.log('   ' + N.toLocaleString() + (FROM ? ' rolls of seeds ' + FROM + '..' + (FROM + N - 1) : ' gallery rolls') + '. */');
console.log('const ODDS={\n' + block + '\n};');

/* a sanity line on stderr so a bad run is obvious */
KEYS.forEach(k => {
  const tot = Object.values(T[k] || {}).reduce((s, c) => s + c, 0);
  console.error(k.padEnd(12) + Object.keys(T[k] || {}).length + ' values, ' + (tot / N * 100).toFixed(1) + '% of rolls');
});
